sudo:
  - required

branches:
  only:
  - master

language:
  - scala

jdk:
  - oraclejdk8

matrix:
  include:
    - env:
      - CI_SCALA_VERSION: 2.11.12
      - CI_COMMAND: ci

script:
  - bin/ci

cache:
  directories:
    - $HOME/.coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
